OnlineShop/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Data;
using OnlineShop.Extensions;
using OnlineShop.Models.Domain;
using OnlineShop.Models.ViewModels.CartViewModels;

namespace OnlineShop.Controllers
{
    public class CartController : Controller
    {
        private readonly ShopDbContext _context;

        public CartController(ShopDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(string returnUrl, Cart cart)
        {
            //Cart cart = GetCart();
            CartIndexViewModel viewModel = new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToCart(Cart cart, int id, string returnUrl)
        {
            //Cart cart = GetCart();
            Product? product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                cart.AddToCart(product, 1);
                HttpContext.Session.Set("cart", cart.CartItems);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteFromCart(Cart cart, int id, string returnUrl)
        {
            //Cart cart = GetCart();
            Product? product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                cart.RemoveFromCart(product);
                HttpContext.Session.Set("cart", cart.CartItems);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteAllFromCart(Cart cart, string returnUrl)
        {
            //Cart cart = GetCart();
            cart.Clear();
            HttpContext.Session.Set("cart", cart.CartItems);
            return LocalRedirect(returnUrl);
        }

        //private Cart GetCart()
        //{
        //    IEnumerable<CartItem>? cartItems = HttpContext.Session.Get<IEnumerable<CartItem>>("cart");
        //    Cart? cart = null;
        //    if (cartItems == null)
        //    {
        //        cart = new Cart();
        //    }
        //    else
        //    {
        //        cart = new Cart(cartItems!);
        //    }
        //    return cart;
        //}
    }
}

OnlineShop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Data;
using OnlineShop.Models;
using OnlineShop.Models.ViewModels.HomeViewModels;
using System.Diagnostics;
using static System.String;

namespace OnlineShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ShopDbContext _context;

        public HomeController(ILogger<HomeController> logger, ShopDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index(string? category, int page = 1)
        {
            IQueryable<Product> products = _context.Products
                .Include(p => p.Category)
                .Include(p => p.Photos);
            if (!IsNullOrEmpty(category))
            {
                products = products.Where(p => p.Category.Title == category);
            }
            int itemsPerPage = 4;
            int pageCount = (int)Math.Ceiling((decimal)products.Count() / itemsPerPage);
            products = products.Skip((page - 1) * itemsPerPage).Take(itemsPerPage);
            HomeIndexViewModel vm = new HomeIndexViewModel
            {
                Products = await products.ToListAsync(),
                Category = category,
                Page = page,
                PageCount = pageCount
            };
            return View(vm);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OnlineShop/ViewComponents/CategoriesMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Data;

namespace OnlineShop.ViewComponents
{
	[ViewComponent]
	public class CategoriesMenuViewComponent : ViewComponent
	{
		private readonly ShopDbContext _context;

		public CategoriesMenuViewComponent(ShopDbContext context)
		{
			_context = context;
		}

		public async Task<IViewComponentResult> InvokeAsync(string? currentCategory)
		{
			List<string> categoryNames = await _context.Products.Include(c => c.Category)
				.Select(c => c.Category.Title)
				.Distinct()
				.ToListAsync();
			return View(new Tuple<List<string>, string?>(categoryNames, currentCategory));
		}
	}
}

OnlineShop/Views/Home/Index.cshtml
@model HomeIndexViewModel
@{
	ViewData["Title"] = "Home Page";
}

<div class="row">
	<div class="col-3">
		<vc:categories-menu current-category="@Model.Category" />
	</div>
	<div class="col">
		<div class="container-fluid">
			<div class="row row-cols-2">
				@foreach (Product product in Model.Products)
				{
					await Html.RenderPartialAsync("_productCard", product);
				}
			</div>
		</div>
		<nav aria-label="pagination example">
			<ul class="pagination">
				@for (int i = 1; i <= Model.PageCount; i++)
				{
					<li class="@(i==Model.Page ? "page-item active" : "page-item" )">
						<a asp-action="Index" asp-route-page="@i" asp-route-category="@Model.Category" class="page-link">@i</a>
					</li>
				}
			</ul>
		</nav>
	</div>
</div>

OnlineShop/Views/Home/_ProductCard.cshtml
@model Product
<div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="@Model.Photos?.FirstOrDefault()?.PhotoUrl"
                 class="img-fluid rounded-start" alt="@Model.Title">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">@Model.Title</h5>
                <p class="card-text">@Model.Price.ToString("# EUR")</p>
                <p class="card-text"><small class="text-muted">@Model!.Category!.Title</small></p>
                <form asp-action="AddToCart" asp-controller="Cart" asp-route-id="@Model.Id" method="post">
                    <input type="hidden" value="@(Context.Request.Path.Value + Context.Request.QueryString.Value)" name="returnUrl" />
                    <button type="submit" class="btn btn-sm btn-success">Add to Cart</button>
                </form>
            </div>
        </div>
    </div>
</div>